core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace="pages")),
    path('recipes/', include('recipes.urls', namespace="recipes")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from .views import HomepageView, AboutpageView, KnowledgeBaseView

app_name = "pages"

urlpatterns = [
    path('help/', KnowledgeBaseView.as_view(), name="help"),
    path('about/', AboutpageView.as_view(), name="about"),
    path('', HomepageView.as_view(), name="home"),
]

products/urls.py
from django.urls import path

urlpatterns = [
    
]

recipes/urls.py
from django.urls import path
from . import views


app_name = "recipes"

urlpatterns = [
    path('', views.RecipePageView.as_view(), name="recipes"),
]

accounts/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models
class Demo(models.Model):
    link = models.URLField(max_length=2000, blank=True, null=True)
    sku = models.CharField(max_length=2000, unique=True)
    name = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()
    all_images = models.TextField()
    main_image = models.URLField(max_length=2000)
    breadcrumbs = models.CharField(max_length=2000)
    title = models.CharField(max_length=2000)
    short_desc = models.CharField(max_length=2000)
    keywords = models.CharField(max_length=2000)
    manufacturer = models.CharField(max_length=255, default="")

    def __str__(self):
        return self.sku
    
    

products/models.py
from django.db import models

class KnifekitsItem(models.Model):
    # Product Data
    link = models.URLField(max_length=5000)
    description = models.TextField()
    main_image = models.URLField(max_length=5000)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    sku = models.CharField(max_length=255)
    name = models.CharField(max_length=1000)
    # Flags
    has_discounts = models.BooleanField(default=False)
    has_video = models.BooleanField(default=False)
    has_discounts = models.BooleanField(default=False)
    #SEO / Meta fields
    title = models.CharField(max_length=1000)
    keywords = models.CharField(max_length=255)
    short_desc = models.CharField(max_length=255)
    # stuff
    discounts = models.TextField()
    image_urls = models.TextField()
    breadcrumbs = models.TextField()
    first_crawl = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sku

recipes/models.py
from django.conf import settings
from django.db import models

"""
- Global
  - Ingredients
  - Recipes
-User
  - Ingredients
  - Recipes
    - Ingredients
    - Directions 
"""

class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    directions = models.TextField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=50) # 1 1/4
    directions = models.TextField(blank=True, null=True)
    unit = models.CharField(max_length=50) # lbs, oz, tsp, cup...
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

# class RecipeImage(models.Model):
    # recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    # name = models.CharField(max_length=200)
    # image = models.ImageField(upload_to="images/recipes/")

pages/forms.py
from django import forms

class ConfiguratorWidget(forms.RadioSelect):
    class Media:
        css = {
            'all': ('configurator.css',)
        }
        js = ('animations.js', 'actions.js')

pages/views.py
from django.core.mail import send_mail
from django.shortcuts import render
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = "pages/homepage.html"

class AboutpageView(TemplateView):
    template_name = "pages/about.html"

class KnowledgeBaseView(TemplateView):
    template_name = "pages/kb.html"

recipes/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from .models import Recipe

class RecipePageView(TemplateView):
    template_name = "recipes/detail-page.html"

class RecipeListView(ListView):
    model = Recipe
    template_name = "recipes/list-view.html"

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipes/detail-view.html"

accounts/templates/accounts/register.html
<div class="form-body">
  <div class="row">
    <div class="form-holder">
      <div class="form-content">
        <div class="form-items">
          <h3>Register Today</h3>
          <p>Fill in the data below.</p>
          <form class="requires-validation" novalidate>

<div class="col-md-12">
            <input class="form-control" type="text" name="name" placeholder="Full Name" required>
<div class="valid-feedback">Username field is valid!</div>
            <div class="invalid-feedback">Username field cannot be blank!</div>
          </div>

          <div class="col-md-12">
            <input class="form-control" type="email" name="email" placeholder="E-mail Address" required>
<div class="valid-feedback">Email field is valid!</div>
            <div class="invalid-feedback">Email field cannot be blank!</div>
          </div>

          <div class="col-md-12">
            <select class="form-select mt-3" required>
<option selected disabled value="">Position</option>
            <option value="jweb">Junior Web Developer</option>
            <option value="sweb">Senior Web Developer</option>
            <option value="pmanager">Project Manager</option>
          </select>
          <div class="valid-feedback">You selected a position!</div>
          <div class="invalid-feedback">Please select a position!</div>
        </div>


        <div class="col-md-12">
          <input class="form-control" type="password" name="password" placeholder="Password" required>
<div class="valid-feedback">Password field is valid!</div>
          <div class="invalid-feedback">Password field cannot be blank!</div>
        </div>


        <div class="col-md-12 mt-3">
          <label class="mb-3 mr-1" for="gender">Gender: </label>

          <input type="radio" class="btn-check" name="gender" id="male" autocomplete="off" required>
<label class="btn btn-sm btn-outline-secondary" for="male">Male</label>

          <input type="radio" class="btn-check" name="gender" id="female" autocomplete="off" required>
<label class="btn btn-sm btn-outline-secondary" for="female">Female</label>

          <input type="radio" class="btn-check" name="gender" id="secret" autocomplete="off" required>
<label class="btn btn-sm btn-outline-secondary" for="secret">Secret</label>
          <div class="valid-feedback mv-up">You selected a gender!</div>
          <div class="invalid-feedback mv-up">Please select a gender!</div>
        </div>

        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
<label class="form-check-label">I confirm that all data are correct</label>
          <div class="invalid-feedback">Please confirm that the entered data are all correct!</div>
        </div>


        <div class="form-button mt-3">
          <button id="submit" type="submit" class="btn btn-primary">Register</button>
        </div>
      </form>
    </div>
  </div>
</div>
</div>
</div>

templates/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="Mike King" />
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon1.ico' %}" />
    <title>{% block title %}BASE.HTML{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block head %}{% endblock head %}
  </head>
  <body>
    {% include 'nav.html' %}
    {% block header %}{% endblock %}
    {% block content %}{% endblock %}
    <footer class="row py-5 bg-dark">
      <p class="m-0 text-center text-white">Copyright &copy; Nynlabs 2021</p>
    </footer>
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="{% url 'pages:home' %}">
      <img src="{% static 'nynlabs.png' %}" width="132" height="34" alt="Nynlabs">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <li class="nav-item"><a class="nav-link" href="{% url 'pages:about' %}">About</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#!">All Products</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <button class="btn btn-outline-dark" type="submit">
          <i class="bi-cart-fill me-1"></i>
          Cart
          <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
        </button>
      </form>
    </div>
  </div>
</nav>

templates/nodes.html
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.css"
      type="text/css"
    />
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis-network.min.js"
    ></script>
      <h1></h1>
    </center>

    <!-- <link rel="stylesheet" href="../node_modules/vis/dist/vis.min.css" type="text/css" />
<script type="text/javascript" src="../node_modules/vis/dist/vis.js"> </script>-->

    <style type="text/css">
      #mynetwork {
        width: 500px;
        height: 500px;
        background-color: #ffffff;
        border: 1px solid lightgray;
        position: relative;
        float: left;
      }
    </style>
  </head>

  <body>
    <div id="mynetwork"></div>

    <script type="text/javascript">
      // initialize global variables.
      var edges;
      var nodes;
      var network;
      var container;
      var options, data;

      function drawGraph() {
          var container = document.getElementById('mynetwork');
          // parsing and collecting nodes and edges from the python
          nodes = new vis.DataSet([{"id": 1, "label": "Mike", "shape": "dot"}, {"id": 2, "label": "Alex", "shape": "dot"}, {"id": 3, "label": "Alisha", "shape": "dot"}]);
          edges = new vis.DataSet([]);
          data = {nodes: nodes, edges: edges};
          var options = {
              "configure": {
                  "enabled": false
              },
              "edges": {
                  "color": {
                      "inherit": true}
                  ,
                  "smooth": {
                      "enabled": false,
                      "type": "continuous"
                  }
              },
              "interaction": {
                  "dragNodes": true,
                  "hideEdgesOnDrag": false,
                  "hideNodesOnDrag": false
              },
              "physics": {
                  "enabled": true,
                  "stabilization": {
                      "enabled": true,
                      "fit": true,
                      "iterations": 1000,
                      "onlyDynamicEdges": false,
                      "updateInterval": 50
                  },
              };
          network = new vis.Network(container, data, options);
          return network;
      }

      drawGraph();
    </script>
  </body>
</html>

templates/pages/_kb-companies.html
<section id="companies" class="section">{% load static %}
   <div class="container">
      <h5>Used by 400+ people from the biggest companies</h5>
      <div class="company-img-container">
         <img class="company-img" src="{% static 'pages/images/amazon.png' %}" alt="">
         <img class="company-img" src="{% static 'pages/images/disney.png' %}" alt="">
         <img class="company-img" src="{% static 'pages/images/kfc.png' %}" alt="">
         <img class="company-img" src="{% static 'pages/images/mailchimp.png' %}" alt="">
         <img class="company-img" src="{% static 'pages/images/shopify.png' %}" alt="">
      </div>
   </div>
</section>
<section id="about" class="section">
   <div class="container-fluid">
      <div class="row">
         <div class="col-xl-4 col-md-10 col-sm-12 offset-xl-1 left">
            <div class="sticky-element">
               <h3 class="text-heading text--violet">WHY CHOOSE US?</h3>
               <h2 class="text-heading">Check out why we’re the best company for all of your
                  needs.
               </h2>
            </div>
         </div>
         <div class="col-xl-6 col-lg-12 col-md-12 col-sm-12 right">
            <div class="row">
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-xs-12 col-flex">
                  <div class="about-card">
                     <img src="{% static 'pages/images/disney.png' %}" alt="Icon">
                     <h4 class="text-heading">Multi-factor authentication.</h4>
                     <p>Increase learner engagement & knowledge retention in higher education and corporate
                        training.
                     </p>
                  </div>
               </div>
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-xs-12 col-flex">
                  <div class="about-card">
                     <img src="{% static 'pages/images/favorites.png' %}" alt="Icon">
                     <h4 class="text-heading">Increase user conversion.</h4>
                     <p>Increase learner engagement & knowledge retention in higher education and corporate
                        training.
                     </p>
                  </div>
               </div>
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-xs-12 col-flex">
                  <div class="about-card">
                     <img src="{% static 'pages/images/utline-with-lifeline.png' %}" alt="Icon">
                     <h4 class="text-heading">Full control over UX.</h4>
                     <p>Increase learner engagement & knowledge retention in higher education and corporate
                        training.
                     </p>
                  </div>
               </div>
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-xs-12 col-flex">
                  <div class="about-card">
                     <img src="{% static 'pages/images/selective.png' %}" alt="Icon">
                     <h4 class="text-heading">Expand user funnel.</h4>
                     <p>Increase learner engagement & knowledge retention in higher education and corporate
                        training.
                     </p>
                  </div>
               </div>
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-xs-12 col-flex">
                  <div class="about-card">
                     <img src="{% static 'pages/images/shield.png' %}" alt="Icon">
                     <h4 class="text-heading">Security compliant.</h4>
                     <p>Increase learner engagement & knowledge retention in higher education and corporate
                        training.
                     </p>
                  </div>
               </div>
               <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-xs-12 col-flex">
                  <div class="about-card">
                     <img src="{% static 'pages/images/shopify.png' %}" alt="Icon">
                     <h4 class="text-heading">Integration in minutes.</h4>
                     <p>Increase learner engagement & knowledge retention in higher education and corporate
                        training.
                     </p>
                  </div>
               </div>
               <div class="col-xl-12 col-lg-12 col-sm-12 about-link-container">
                  <a class="btn primary-button" href="#">View more choices <i
                     class="fas fa-arrow-right"></i></a>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

templates/pages/_kb-faq.html
<section id="faq" class="section">
   <div class="container">
      <div class="row">
         <div class="col-lg-6 col-md-12 offset-lg-3 title-section">
            <h2 class="text-heading section-heading">Frequently Asked Questions</h2>
            <p>FAQ is suppose to be an online document that poses a series of common
               questions and answers on a specific topic.
            </p>
         </div>
         <div class="col-lg-4 col-md-5 col-sm-12">
            <div class="card sticky-element">
               <ul class="list-group list-group-flush">
                  <h4 class="text-heading">Quick Navigation</h4>
                  <a href="#"
                     class="list-group-item list-group-item-action d-flex justify-content-between align-items-center active"
                     aria-current="true">
                  License
                  <i class="fas fa-chevron-right"></i>
                  </a>
                  <a href="#"
                     class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                  Pricing & Support
                  <i class="fas fa-chevron-right"></i>
                  </a>
                  <a href="#"
                     class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                  Purchasing Online
                  <i class="fas fa-chevron-right"></i>
                  </a>
                  <a href="#"
                     class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                  Returns
                  <i class="fas fa-chevron-right"></i>
                  </a>
               </ul>
            </div>
         </div>
         <div class="col-lg-8 col-md-7 col-sm-12">
            <div class="accordion" id="accordionExample">
               <div class="accordion-item">
                  <h2 class="accordion-header" id="headingOne">
                     <button class="accordion-button" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                     What is your refund policy and terms and conditions?
                     </button>
                  </h2>
                  <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                     data-bs-parent="#accordionExample">
                     <div class="accordion-body">
                        We comply fully with KB’s refund policy. We issue refunds for the reasons KB
                        permits us to give refund and we don’t issue refunds on the cases KB does not
                        guarantee refunds. Please check KB’s refund policy:
                     </div>
                  </div>
               </div>
               <div class="accordion-item">
                  <h2 class="accordion-header" id="headingTwo">
                     <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                     How many shortcodes/blocks/elements are there in Rogan?
                     </button>
                  </h2>
                  <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                     data-bs-parent="#accordionExample">
                     <div class="accordion-body">
                        There are over 200 shortcodes/blocks/elements in Rogan WordPress Theme. You can use
                        any block/element into any page as you want.
                     </div>
                  </div>
               </div>
               <div class="accordion-item">
                  <h2 class="accordion-header" id="headingThree">
                     <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                     Is Rogan Gutenberg compatible and latest WordPress supported?
                     </button>
                  </h2>
                  <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                     data-bs-parent="#accordionExample">
                     <div class="accordion-body">
                        Yes, SaasLand is compatible with Gutenberg.
                     </div>
                  </div>
               </div>
               <div class="accordion-item">
                  <h2 class="accordion-header" id="headingFour">
                     <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                     How many websites can I use Rogan in with a regular license?
                     </button>
                  </h2>
                  <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour"
                     data-bs-parent="#accordionExample">
                     <div class="accordion-body">
                        According to KB’s licensing, you can use SaasLand or any other theme on only one website. If you want to use it on multiple websites, you must buy multiple licenses. 
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>
<h3>Testimonials Section</h3>
Next, let's add a simple customer testimonial showcasing user experience with the knowledge base page. We're going to use bootstrap's flexbox here in order to manipulate the responsive view of two of the column testimonial boxes.
<section id="testimonials" class="section">
   <div class="space-between-blocks">
      <div class="container">
         <div class="row">
            <div class="col-md-8 offset-md-2 title-section">
               <h3 class="text-heading text--violet">WHAT THEY SAY ABOUT US</h3>
               <h2 class="text-heading">Approved by more than 300 customer like you all aroung the world.</h2>
            </div>
            <div class="row px-2 pt-4">
               <div class="col-lg-6 pb-5">
                  <div class="testimonial-card-1">
                     <p class="testimonial-card-1__paragraph">Knowledge base is one of the critical tools for both customer support and internal knowledge management. That’s why KB always aim to use the best technology available and do periodic market reviews to make sure we are using the latest and the most advanced tools. </p>
                     <div class="testimonial-blk-person">
                        <div><img class="testimonial-blk-person__avatar"
                           src="img/mark-doe.jpg"></div>
                        <div class="px-2"></div>
                        <div class="flex-grow-1 d-flex flex-column"><span class="testimonial-blk-person__rating"><i
                           class="fas fa-star"></i><i class="fas fa-star"></i><i
                           class="fas fa-star"></i><i class="fas fa-star"></i><i
                           class="fas fa-star"></i></span><span class="testimonial-blk-person__name my-1">Mark
                           Doe</span><span class="testimonial-blk-person__info">XYZ Company</span>
                        </div>
                     </div>
                     <span class="testimonial-card-1__quote-symbol"><i
                        class="fas fa-quote-left"></i></span>
                  </div>
               </div>
               <div class="col-lg-6 pb-5">
                  <div class="testimonial-card-1">
                     <p class="testimonial-card-1__paragraph">My experience with KB goes back several years. I've had a few KB programs over the years because I create and manage multiple websites. I recently made the decision to have all of our KB's convert to KB and I've been very, very pleased.</p>
                     <div class="testimonial-blk-person">
                        <div><img class="testimonial-blk-person__avatar"
                           src="img/chris-doe.jpg"></div>
                        <div class="px-2"></div>
                        <div class="flex-grow-1 d-flex flex-column"><span class="testimonial-blk-person__rating"><i
                           class="fas fa-star"></i><i class="fas fa-star"></i><i
                           class="fas fa-star"></i><i class="fas fa-star"></i><i
                           class="fas fa-star"></i></span><span
                           class="testimonial-blk-person__name my-1">Chris Doe</span><span
                           class="testimonial-blk-person__info">CHO Digital</span></div>
                     </div>
                     <span class="testimonial-card-1__quote-symbol"><i
                        class="fas fa-quote-left"></i></span>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

templates/pages/_kb-footer.html
<section id="contact" class="section">
   <div class="container">
      <div class="row">
         <div class="col-md-6 offset-md-3 title-section">
            <h2 class="text-heading section-heading">Get More Help</h2>
            <p>Here we have more ways to get help from real humans.</p>
         </div>
      </div>
      <div class="row">
         <div class="col-lg-3 col-sm-6 col-xs-12">
            <a href="#">
               <div class="card">
                  <i class="fas fa-user-friends"></i>
                  <p>Forums</p>
               </div>
            </a>
         </div>
         <div class="col-lg-3 col-sm-6 col-xs-12">
            <a href="#">
               <div class="card">
                  <i class="fab fa-twitter"></i>
                  <p>Twitter Support</p>
               </div>
            </a>
         </div>
         <div class="col-lg-3 col-sm-6 col-xs-12">
            <a href="#">
               <div class="card">
                  <i class="fas fa-envelope"></i>
                  <p>Email Us</p>
               </div>
            </a>
         </div>
         <div class="col-lg-3 col-sm-6 col-xs-12">
            <a href="#">
               <div class="card">
                  <i class="fas fa-phone-alt"></i>
                  <p>Phone Call</p>
               </div>
            </a>
         </div>
      </div>
   </div>
</section>
<footer>
   <div class="container">
      <div class="row">
         <div class="col-md-9 col-sm-12  left">
            <ul>
               <li>
                  <a href="#" class="nav-link">Home</a>
               </li>
               <li>
                  <a href="#" class="nav-link">Docs</a>
               </li>
               <li>
                  <a href="#" class="nav-link">Changelog</a>
               </li>
               <li>
                  <a href="#" class="nav-link">Purchase</a>
               </li>
            </ul>
         </div>
         <div class="col-md-3 col-sm-12  right footer-logo ">
            <a id="navbar-brand" class="navbar-brand " href="#">KB</a>
         </div>
      </div>
   </div>
</footer>

templates/pages/_kb-header.html
<section id="header">{% load static %} {% load static %}
   <div class="header-content">
      <div class="container-fluid container-xl hero">
         <div class="row">
            <div class="col-sm-12 col-md-5 svg-header-container ">
               <img src="{% static 'pages/images/illustration2.svg' %}" alt="Mobile SVG illustration">
            </div>
            <div class="col-sm-12 col-md-7 header-content-container">
               <div>
                  <h1 class="text--white text-heading">Build a business with a stunning <span class="text--green">knowledge base</span>. What can we help you <span class="text--green">find</span>?</h1>
                  <p class="header-content-text">KB is a fully featured knowledge base theme for any products and services.</p>
                  <div class="search-container">
                     <form action="#">
                        <input class="form-control" placeholder="Search for something">
                        <button class="btn secondary-button" type="submit"><i
                           class="fas fa-search"></i></button>
                     </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <svg class="wave" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#ffffff" fill-opacity="1"
         d="M0,32L34.3,48C68.6,64,137,96,206,96C274.3,96,343,64,411,48C480,32,549,32,617,80C685.7,128,754,224,823,234.7C891.4,245,960,171,1029,160C1097.1,149,1166,203,1234,224C1302.9,245,1371,235,1406,229.3L1440,224L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z">
      </path>
   </svg>
</section>

templates/row.html
<div class="row">
link
sku
name
price
description
images
main_image
breadcrumbs
title
short_desc
keywords
manufacturer
</div>